---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(readxl)
library(gridExtra)
library(gtsummary)
library(pak)
library(kableExtra)
library(knitr)
library(scales)
library(pandoc)
library(ggrepel)
library(ggplot2)
```


```{r work, include=FALSE}

datafile = read_xlsx("Daily Log 12-24-2024 2-21-48.xlsx", sheet = "All Data") 

data = datafile %>%
  mutate(
    Name = paste(`First Name`, `Last Name`), .keep = "unused", .after = "ArmCare ID"
  )

pitchers = paste(datafile$`First Name`, datafile$`Last Name`) %>% unique()

pitcher = reactive({
  filter(datafile, `Last Name` == input$pitcher) %>% 
    mutate(
    `Exam Date` = as.Date(`Exam Date`, format = "%m/%d/%Y")
  ) %>% arrange(`Exam Date`)
})


PitcherArmStats = reactive ({
  pitcher() %>% 
  summarise(
    "Avg Arm Score" = mean(`Arm Score`),
    "Avg Total Strength" = mean(`Total Strength`),
    "Avg IR RS" = mean(`IRTARM RS`)*100,
    "Avg ER RS" = mean(`ERTARM RS`)*100,
    "Avg Scaption RS" = mean(`STARM RS`)*100
    ) %>% 
    kable(format = "html",  linesep = "", label = "Pitch Stats", align = 'c') %>%
  kable_styling(latex_options = "HOLD_position", position = "center", font_size = 20) %>% 
  column_spec(1, color = case_when(
    PitcherArmStats$`Avg Arm Score` > 70 ~ 'black',
    PitcherArmStats$`Avg Arm Score` > 50 ~ 'yellow',
    PitcherArmStats$`Avg Arm Score` <= 50 ~ 'red',
  )) %>% 
  column_spec(3, color = case_when(
    PitcherArmStats$`Avg IR RS` > 20 ~ 'black',
    PitcherArmStats$`Avg IR RS` == 20 ~ 'yellow',
    PitcherArmStats$`Avg IR RS` < 20 ~ 'orange',
    PitcherArmStats$`Avg IR RS` < 15 ~ 'red',
  )) %>% 
  column_spec(4, color = case_when(
    PitcherArmStats$`Avg ER RS` > 20 ~ 'black',
    PitcherArmStats$`Avg ER RS` == 20 ~ 'yellow',
    PitcherArmStats$`Avg ER RS` < 20 ~ 'orange',
    PitcherArmStats$`Avg ER RS` < 15 ~ 'red',
  )) %>% 
  column_spec(5, color = case_when(
    PitcherArmStats$`Avg Scaption RS` > 15 ~ 'black',
    PitcherArmStats$`Avg Scaption RS` == 15 ~ 'yellow',
    PitcherArmStats$`Avg Scaption RS` < 15 ~ 'orange',
    PitcherArmStats$`Avg Scaption RS` < 10 ~ 'red',
  ))
}) 

```


Page 1 {data-orientation=rows}
=====================================  

Column {data-height=50}
-------------------------------------

```{r}
selectInput("pitcher", "Pitcher", c(pitchers))
```


Row {data-height=200}
-------------------------------------
    
### Arm Care Stat Averages
    
```{r}
PitcherArmStats
```
   
Column {data-width=400}
-------------------------------------
   
### Chart 2

```{r}
```   
 
### Chart 3
    
```{r}
```

Page 2 {data-orientation=rows}
=====================================     
   
Row {data-height=600}
-------------------------------------

### Chart 1

```{r}
```

Row {data-height=400}
-------------------------------------
   
### Chart 2

```{r}
```   
    
### Chart 3

```{r}
```






Outputs
--------------------------------
```{r}



```


